Repository ganeti/ganeti, pull requests merged in 2019-11, with the labels that each got.

#1403 RPC: prevent cURL from sending Expect: 100-Continue
  src/Ganeti/Rpc.hs
Labels: Performance, bug, cla: yes

#1391 Support build in separate directory from RO source dir.
  Makefile.am
  configure.ac
Labels: cla: yes

#1402 Build using GHC 8.6/network 2.8
  cabal/ganeti.template.cabal
  src/Ganeti/BasicTypes.hs
  src/Ganeti/Compat.hs
  src/Ganeti/Errors.hs
Labels: Compatibility, cla: yes

#1406 QuickCheck 2.12 compatibility
  cabal/ganeti.template.cabal
  test/hs/Test/Ganeti/JQScheduler.hs
  test/hs/Test/Ganeti/TestCommon.hs
Labels: cla: yes
