Repository ganeti/ganeti, pull requests merged in 2021-01, with the labels that each got.

#1528 Add KVM parameter to toggle QEMU's debug-threads=on|off feature
  lib/hypervisor/hv_kvm/__init__.py
  man/gnt-instance.rst
  src/Ganeti/Constants.hs
Labels: Ganeti 3.1

#1556 KVM: work around dynamic auto-ro for disk hotplug
  lib/hypervisor/hv_kvm/__init__.py
  lib/hypervisor/hv_kvm/monitor.py
Labels: Backport to 3.0

#1558 backport: KVM: work around dynamic auto-ro for disk hotplug
  lib/hypervisor/hv_kvm/__init__.py
  lib/hypervisor/hv_kvm/monitor.py
Labels: Backport to 3.0

#1557 backport: kvm: get known instances from runtime and not PID files
  lib/hypervisor/hv_kvm/__init__.py
Labels: Backport to 2.16

#1561 hotplug: set disk parameters
  lib/hypervisor/hv_kvm/__init__.py
Labels: Backport to 3.0

#1564 backport: hotplug: set disk parameters
  lib/hypervisor/hv_kvm/__init__.py
Labels: Backport to 3.0
